defaults:
  resources:
    instance-type: C7

jobs:
  cloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/Jameshskelton/workflows-upload-dataset
  downloadData:
    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      models:
        type: dataset
        with:
          ref: ds2613iefqca1y7
    uses: script@v1
    with:
      script: |-
        cd ../outputs/models/
        mkdir scheduler
        cd scheduler/
        wget https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/scheduler/scheduler_config.json
        cd ..
        mkdir text_encoder_2
        cd text_encoder_2
        wget https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/text_encoder_2/config.json
        wget -O model.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/text_encoder_2/model.safetensors
        cd ..
        mkdir text_encoder
        cd text_encoder
        wget -O config.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/text_encoder/config.json
        wget model.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/text_encoder/model.safetensors
        cd ..
        mkdir unet
        cd unet
        wget -O config.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/unet/config.json
        wget -O model.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/unet/diffusion_pytorch_model.safetensors
        cd ..
        mkdir vae
        cd vae
        wget -O config.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/vae/config.json
        wget -O diffusion_pytorch_model.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae/diffusion_pytorch_model.safetensors
        cd ..
        mkdir vae_1_0
        cd vae_1_0
        wget -O config.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/vae_1_0/config.json
        wget -O diffusion_pytorch_model.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_1_0/diffusion_pytorch_model.safetensors
        cd ..
        mkdir vae_decoder
        cd vae_decoder
        wget -O config.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/vae_decoder/config.json
        wget -O model.onnx https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_decoder/model.onnx
        wget -O openvino_model.onnx https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_decoder/openvino_model.bin
        wget -O openvino_model.xml https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_decoder/openvino_model.xml
        cd ..
        mkdir vae_encoder
        cd vae_encoder
        wget -O config.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/vae_encoder/config.json
        wget -O model.onnx https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_encoder/model.onnx
        wget -O openvino_model.onnx https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_encoder/openvino_model.bin
        wget -O openvino_model.xml https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/vae_encoder/openvino_model.xml
        cd ..
        wget -O model_index.json https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/raw/main/model_index.json
        wget -O sd_xl_base_1.0.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
      image: paperspace/nb-pytorch:22.02-py3
